version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql-server
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
    driver: local